version: '3'
services:
  dev-db:
    image: postgres
    environment:
      POSTGRES_USER: abc
      POSTGRES_PASSWORD: DEVELOPMENT_PASSWORD
      POSTGRES_DB: DEVELOPMENT_DB
    ports:
      - 5434:5432
    networks:
      - dev_network
  # test-db:
  #   image: postgres
  #   environment:
  #     POSTGRES_USER: TEST_DB_USER
  #     POSTGRES_PASSWORD: TEST_DB_PASSWORD
  #     POSTGRES_DB: TEST_DB
  #   ports:
  #     - 5435:5432
  #   networks:
  #     - de_network
networks:
  dev_network:
